<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Create Users</title>
    <link rel="stylesheet" type="text/css" href="../css/style.css" media="all">
    <link rel="stylesheet" href="../index_files/mbcsmbmcp.css" type="text/css" />
    <link  rel="stylesheet" href="../css/bootstrap.min.css">


    <!--<script type="text/javascript" src="../js/view.js"></script>-->



    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>

    <!--<script src="../js/jquery.min.js"></script>-->

    <!--<script src="../js/bootstrap.min.js"></script>-->
    <script>
        $(function(){
            $("#mbmcpebul_wrapper").load("nav_left.html");
        });

          var proId= '<?php echo $_GET['pro_id'];?>';
      //  alert(proId);
    </script>


    <style>
        .alert {
            padding: 20px;
            background-color: #f44336;
            color: white;
        }

        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

        .closebtn:hover {
            color: black;
        }
    </style>
</head>
<body id="main_body"  >


    <div class="col-md- 2">
        <img src="../images/finallogo.png" width="200" height="150">
        <!--<img id="top" src="../images/top.png" alt="">-->
    </div>
    <div class="col-md-12">
        <div class="col-md-2"  id="mbmcpebul_wrapper" style="width: 136px;">

        </div>
        <div class="col-md-5" style="margin-left: 100px" id="form_container">
            <h1><a>Create Notification</a></h1>
            <form id="form_47332" class="appnitro"  method="post" action="/pms/php/upload_files.php" enctype="multipart/form-data">
                <div class="form_description">
                    <h2>Add user to project</h2>
                    <p></p>
                </div>
                <ul >

<!--                    <li id="li_6" >-->
<!--                        <label class="description" for="stu_id">Select User </label>-->
<!--                        <div>-->
<!--                            <select class="element select medium" id="stu_id" name="stu_id">-->
<!---->
<!--                            </select>-->
<!--                        </div>-->

                    <!--                    </li>-->


                    <li id="li_7" >
                        <label class="description" for="pro_id"> Project </label>
                        <div>
                            <input type="text" name="pro1" id="pro1" style="display: none;"/>
                        </div>
                    </li>

                    <li id="li_7" >
                        <label class="description" for="pro_id"> Project </label>
                        <div>
                            <input type="text" name="pro" id="pro" disabled/>
                        </div>
                    </li>

                    <li id="li_7" >
                        <label class="description" for="pro_id"> File Name </label>
                        <div>
                            <input type="text" name="name" id="name" />
                        </div>
                    </li>

                    <li id="li_7" >
                        <label class="description" for="pro_id"> upload file </label>
                        <div>
                            <input type="file" name="file" id="fileToUpload">                        </div>
                    </li>



                    <li class="buttons">
                        <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                    </li>
                </ul>
            </form>
<h3>Download project files</h3>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Download</th>
                </tr>
                </thead>
                <tbody id="up">


                </tbody>
            </table>


        </div>

<!--        <div class="col-md-3 frame" >-->
<!--            <ul id="newUL"></ul>-->
<!--            <div>-->
<!--                <div class="msj-rta macro" style="margin:auto">-->
<!--                    <div class="text text-r" style="background:whitesmoke !important">-->
<!--                        <input class="mytext" placeholder="Type a message"/>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->


    </div>
    <!--<div id="footer">-->
        <!--Generated by <a> Apollo X</a>-->
    <!--</div>-->
    <!--<img id="bottom" src="../images/bottom.png" alt="">-->

</body>
</html>

<script>
    // wait for the DOM to be loaded
    $(document).ready(function() {
        // bind 'myForm' and provide a simple callback function
        $('#form_47332').ajaxForm(function(response) {
            if(response=='success'){
               alert("file uploaded");
                location.reload();

            }else{
                alert("something is wrong");
            }
        });



        $.ajax({
            url: '/pms/php/user_pro.php',
            dataType: 'JSON',
            //data: data,
            method: 'POST',
            async: true,
            success: function callback(data) {
                var str='<option value="" selected="selected"></option>';
                var str1=' <option value="" selected="selected"></option>';
                for(var i=0;i<data.pro.length;i++){
                    if(data.pro[i].projectID==proId){
                        $("#pro").val(data.pro[i].name);
                        $("#pro1").val(data.pro[i].projectID);

                    }
                   // str=str+'<option value="'+data.pro[i].projectID+'" >'+data.pro[i].name+'</option>';
                }

//                for(var i=0;i<data.user.length;i++){
//                    str1=str1+'<option value="'+data.user[i].userID+'" >'+data.user[i].username+'</option>';
//                }

                $("#pro_id").html(str);
               // $("#stu_id").html(str1);


            }
        });

        $.ajax({
            url: '/pms/php/download_file.php?id='+proId,
            dataType: 'JSON',
            //data: data,
            method: 'POST',
            async: true,
            success: function callback(data) {
                var strr=''
                for(var i=0;i < data.length;i++) {
                    strr = strr + ' <tr>' +
                    '<td>' + data[i].name + '</td>' +
                    '<td><a href="' + data[i].file_path + '">Click here to download file</a></td>' +
                    '</tr>';
                }

                $("#up").html(strr);


            }
        })



    });


</script>