

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>


<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="../index_files/mbcsmbmcp.css" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Create Your Project Here</title>
<link rel="stylesheet" type="text/css" href="../css/view.css" media="all">
    <link  rel="stylesheet" href="../css/bootstrap.min.css">

<script type="text/javascript" src="../js/view.js"></script>
<script type="text/javascript" src="../js/calendar.js"></script>
    <script src="../js/jquery.min.js"></script>

    <script src="../js/bootstrap.min.js"></script>
    <script>
        $(function(){
            $("#mbmcpebul_wrapper").load("nav_left.html");
        });
        var proId= '<?php echo $_GET['pro_id'];?>';
    </script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>

</head>

<script>
    // wait for the DOM to be loaded
    $(document).ready(function() {
        // bind 'myForm' and provide a simple callback function
        $('#form_47328').ajaxForm(function(response) {
            if(response=='success'){
                alert('stage created')
            }else {
                alert('something is wrong')
            }
        });


        $.ajax({
            url: '/pms/php/viewStuProject.php',
            dataType: 'JSON',
            //data: data,
            method: 'POST',
            async: true,
            success: function callback(data) {
                var str='<option value="" selected="selected"></option>';

                for(var i=0;i<data.length;i++) {
                    if (data[i].projectID == proId){
                        str = str + '<option value="' + data[i].projectID + '" >' + data[i].name + '</option>';
                }
                }



                $("#pro_id").html(str);


            }
        });



    });


</script>

<body id="main_body" >
<div class="col-md- 2">
    <img src="../images/finallogo.png" width="200" height="150">

<img id="top" src="../images/top.png" alt="">
</div>
<div class="col-md-12">

    <div class="col-md-2"  id="mbmcpebul_wrapper" style="width: 136px;">

    </div>

	<div class="col-md-10" style="margin-left: 100px" id="form_container">
		<h1><a>Create stage Here</a></h1>
		<form id="form_47328" class="appnitro"  method="post" action="/pms/php/createstage.php">
					<div class="form_description">
			<h2>Create Your Project Here</h2>
			<p></p>
		</div>						
			<ul >

                <li id="li_7" >
                    <label class="description" for="element_7">Select Project </label>
                    <div>
                        <select class="element select medium" id="pro_id" name="pro_id">


                        </select>
                    </div>
                </li>

                <li id="li_2" >
		<label class="description" for="element_2">Stage Name </label>
		<div>
			<input type="text" id="element_2" name="name" class="element textarea medium">
		</div> 
		</li>
                <li id="li_3" >
		<label class="description" for="element_3_1">Start Date </label>
		<span>
			<input id="element_3_1" name="start" class="element text" size="2" maxlength="2" value="" type="date">
			<label for="element_3_1">MM</label>
		</span>

		 
		</li>

                <li id="li_4" >
		<label class="description" for="element_4_1">End Date </label>
		<span>
			<input id="element_4_1" name="end" class="element text" size="2" maxlength="2" value="" type="date">
		</span>


		 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="47328" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>
</div>
</div>
		<!--<div id="footer">-->
			<!--<a>Generated by Apollo X</a>-->
		<!--</div>-->
	</div>



	<!--<img id="bottom" src="../images/bottom.png" alt="">-->
	</body>
</html>