<?php
session_start();
$loc='http://' . $_SERVER['HTTP_HOST'];
if(isset($_SESSION['username'])){
    $usr=$_SESSION['username'];
	//	header("Location:".$loc."/pms/");

}
?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Create Users</title>
<link rel="stylesheet" type="text/css" href="../css/style.css" media="all">
    <link rel="stylesheet" href="../index_files/mbcsmbmcp.css" type="text/css" />
    <link  rel="stylesheet" href="../css/bootstrap.min.css">


    <script type="text/javascript" src="../js/view.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
	
	<script>
        // wait for the DOM to be loaded
        $(document).ready(function() {
            // bind 'myForm' and provide a simple callback function
            $('#form_47332').ajaxForm(function(response) {
                if(response=='success'){
		    //$("#errormessage").html("<h6 style='color: green'>"+response+"</h6>");
                    alert('user created');
                    location.reload();

                }else{
                   alert(response);
               }
            });


            
        });

       var usr='<?php if(isset($usr)){echo 'exist';}else{echo 'no';}?>';
     //   alert(usr);
    </script>
    <!--<script src="../js/jquery.min.js"></script>-->

    <!--<script src="../js/bootstrap.min.js"></script>-->
    <script>
        $(function(){
            if(usr=='exist') {
                $("#mbmcpebul_wrapper").load("../nav_left.html");
            }else{
                $("#mbmcpebul_wrapper").load("../nav_left_new.html");

            }
        });
    </script>

</head>
<body id="main_body" >

<div class="col-md- 2">
	<img src="../images/finallogo.png" width="200" height="150">
	<!--<img id="top" src="../images/top.png" alt="">-->
</div>

    <div class="col-md-12">

        <div class="col-md-2"  id="mbmcpebul_wrapper" style="width: 136px;">

        </div>

        <div class="col-md-10" style="margin-left: 100px" id="form_container">
	
		<h1><a>Create Users</a></h1>
		<form id="form_47332" class="appnitro"  method="post" action="/pms/php/createuser.php">
					<div class="form_description">
			<h2>Create Users</h2>
			<p></p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">User Name</label>
		<div>
			<input id="element_1" name="username" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">First Name </label>
		<div>
			<input id="element_2" name="fname" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Last Name </label>
		<div>
			<input id="element_3" name="lname" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Email </label>
		<div>
			<input id="element_4" name="email" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_7" >
		<label class="description" for="element_7">User Type </label>
		<div>
		<select class="element select medium" id="element_7" name="type"> 
			<option value="" selected="selected"></option>
			<option value="admin" >Admin</option>
			<option value="student" >Student</option>

		</select>
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Password </label>
		<div>
			<input type="password" id="pass1" name="pass" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_6" >
		</li>
			
					<li class="buttons">
			    <!--<input type="hidden" name="form_id" value="47332" />-->
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>
        </div>
    </div>


    <div id="errormessage"></div>

		<!--<div id="footer">-->
			<!--Generated by <a> Apollo X</a>-->
		<!--</div>-->
	<!--<img id="bottom" src="../images/bottom.png" alt="">-->
	</body>
</html>